import "./globals.css";
import Sidebar from "./menu/page";
import { GlobalStateProvider } from '../contexts/users';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className="h-screen w-screen">
        <GlobalStateProvider>
          <div className="flex h-full w-full">
            
            <div className="w-1/4 bg-menuColor p-16">
              <Sidebar />
            </div>

            <div className="w-3/4">
              {children}
            </div>

          </div>
        </GlobalStateProvider>
      </body>
    </html>
  );
}